CREATE OR REPLACE VIEW "VW_PROGRAM" AS
    SELECT
        "SPS"."ID"         AS "SECTION_ID",
        "SPS"."NAME"       AS "SECTION",
        "SP"."ID"          AS "PROGRAM_ID",
        "SP"."DESCRIPTION" AS "DESCRITPTION"
    FROM "SYSTEM_PROGRAM_SECTION" "SPS"
    JOIN "SYSTEM_PROGRAM" "SP" ON "SP"."SECTION" = "SPS"."ID";
