INSERT INTO "SYSTEM_PROGRAM_SECTION" ("NAME") 
    SELECT 'Administração'
    WHERE
        NOT EXISTS (SELECT "NAME" FROM "SYSTEM_PROGRAM_SECTION" WHERE "NAME" = 'Administração');

INSERT INTO "SYSTEM_PROGRAM_SECTION" ("NAME") 
    SELECT 'Logs'
    WHERE
        NOT EXISTS (SELECT "NAME" FROM "SYSTEM_PROGRAM_SECTION" WHERE "NAME" = 'Logs');
