INSERT INTO "SYSTEM_GROUP" ("NAME", "CREATED_BY")
    SELECT 
        'Webmaster', (SELECT "ID" FROM "SYSTEM_USER" WHERE "LOGIN" = 'mauro.miranda' LIMIT 1)
    WHERE
        NOT EXISTS (SELECT "NAME" FROM "SYSTEM_GROUP" WHERE "NAME" = 'Webmaster');