#!/usr/bin/php
<?php

if(php_sapi_name() !== 'cli'){
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Cmd\App;
use Console\NameController;
use Console\SetupController;

$app = new App();

$app->registerController('hello', new NameController($app));
$app->registerController('status', new SetupController($app));

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getPrinter()->display("usage: php solluzi hello [ parameter ]");
});

$app->runCommand($argv);

